services:
  postgres:
    image: postgres:latest
    container_name: nastenysh-is-labs-postgres
    environment:
      POSTGRES_USER: s368643
      POSTGRES_PASSWORD: qwerty12345
      POSTGRES_DB: studs
    ports:
      - "15432:5432"
  backend:
    build: .
    container_name: nastenysh-is-labs-backend
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://nastenysh-is-labs-postgres:5432/studs
      - SPRING_DATASOURCE_USERNAME=s368643
      - SPRING_DATASOURCE_PASSWORD=qwerty12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_CLOUD_AWS_CREDENTIALS_ACCESS_KEY=${SPRING_CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      - SPRING_CLOUD_AWS_CREDENTIALS_SECRET_KEY=${SPRING_CLOUD_AWS_CREDENTIALS_SECRET_KEY}
    ports:
      - "8080:8080"